### ISSUE TITLE
Implement buttons to Close/Reopen the issue

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-apps#233]
Only for an existing issue in readonly mode. Buttons should act in the same way as the Open/Closed dropdown acts now.

When in "Open" state: show "Close Issue" button (darkgray color, as now) next to "Edit Issue"
![image](https://user-images.githubusercontent.com/11612490/32555426-022cb706-c49d-11e7-8fca-77f671828f93.png)

When in "Closed" state: show "Reopen Issue" button (green color)
![image](https://user-images.githubusercontent.com/11612490/32555461-1bf03564-c49d-11e7-9c11-14a691d26a9b.png)

**Comment by alansemenov** [comment]
Some small things that popped up during testing of #232. Writing them here so that I could close the other one:

* Tabs should use regular XP styling, like the one we have in the Insert Link dialog for example. Specifically, active tab caption must be in blue and there should be no on-hover dark-grey background.
![image](https://user-images.githubusercontent.com/11612490/33475176-c0822654-d67d-11e7-8c5a-4a018e74973b.png)

* When the Content selector is focused, it has a black border. Again, there should be no custom styling here - use the regular styling for focused fields.
Now:
![image](https://user-images.githubusercontent.com/11612490/33475233-f92c81c0-d67d-11e7-8ed3-5116f998b79a.png)
Was:
![image](https://user-images.githubusercontent.com/11612490/33475250-118da118-d67e-11e7-8ef6-d34e4104d393.png)

* We need to re-center the dialog in these three cases (we didn't have it before, but we should):
-- when the dialog opens
-- after switching to Edit mode
-- after clicking the "Show/hide dependent items" link in the item list

* Cancel button is blue and Edit is grey. It should be the other way around (see screenshots)

* There's a strange empty space under the Item list when creating a new issue, that should not be there:

![image](https://user-images.githubusercontent.com/11612490/33475499-f6052924-d67e-11e7-9f42-84062758f334.png)

* When creating a new issue without items, there's an instant vertical scrollbar although there's enough space to not have it. It's ok to have it when there's item list on the tab, but not in this case:

![image](https://user-images.githubusercontent.com/11612490/33475631-619d8d0c-d67f-11e7-8d3f-012611e8051d.png)

* Bug: If I select 2 items in the grid, click "Create Issue", then close the dialog, unselect the items and go to Create Issue again then the button says "Create Issue (2)" even though there are no items. Seems like the button caption is not refreshed:

* Bug: Dropdown of the content selector is cut off:
![image](https://user-images.githubusercontent.com/11612490/33475974-8a95b21a-d680-11e7-9474-a43f5c766ad2.png)

* Bug: Number of child items inside "Show/hide dependent items (X)" link is not updated after toggling the tree icon on/off

**Comment by alansemenov** [comment]
Another important thing - it should not be possible to publish an issue that contains invalid items. In the "old" version we disabled the Publish button and showed the tooltip, should be the same in the new version:

![image](https://user-images.githubusercontent.com/11612490/33477574-6e9be254-d686-11e7-9495-bba2eb269000.png)

**Comment by pmi** [comment]
Done the fixes, hope I didn't miss anything.
Some worked ok for me, but that may be due to the fixes for the previous ones.
Also the ones regarding CreateIssueDialog were actually not related to IssueDetailsDialog but I fixed them anyway.

**Comment by alansemenov** [comment]
Almost perfect, but the buttons are still wrong. Close should be darkgray and Edit should be blue.

Found a few new bugs too:

* Seems like the list of dependent items is limited by 20 items. Note numbers in "Items (119)" and "Hide dependent items (20)" below:

![image](https://user-images.githubusercontent.com/11612490/33529350-fed88562-d86f-11e7-867a-0004ea2c6ca5.png)

* Seems like dependent items are not fetched right away when you create a new issue. If you look at the screenshot below, it says "Items (7)" but the list only shows 5 main items. 7 is correct because Features has 2 dependent items, but they are not shown. If you click the tree toggler next to Features twice then the required dependencies will show up.

![image](https://user-images.githubusercontent.com/11612490/33529393-a6e64f32-d870-11e7-9652-d5a5f3a5be0f.png)

![image](https://user-images.githubusercontent.com/11612490/33529414-eb1e3278-d870-11e7-9696-aac07fe3b3ee.png)

* After you create a new issue, there are two "X" icons in the modal dialog (see screenshot above)
